### ISSUE TITLE
Explanation for usage of betweenLaneNormalization and the choice of k

### ISSUE THREAD

**Issue by chrarnold** [mikelove/preNivolumabOnNivolumab#2]
Hi Michael!

Could you add some comments and reasoning why `betweenLaneNormalization` was used in your code when running RUVSeq ? In particular, I am wondering:
1. What is the general rationale, why is it necessary? Just as a "quick" way to correct for library size differences without using the previously calculated DESeq size factors? Wouldn't it be "cleanest" to use the size factors, as they have been used to derive the p-values also in the DESeq analysis?
2. Does the exact method (median, upper, full) make a big difference usually? I am trying to get a better grasp on when to choose which, any experiences here? Should upper be a reasonable default, and how to QC how well this worked?

Also, I wonder about the right choice of `k`, the number of factors. 
3. I understand this may not be trivial, but how guys usually go about it? Setting it to 5 or 10 seems to be a sensible default, but also here I wonder about how to QC this. 
4. Does k depend on the sample size also, or this is really unpredictable and has to be determined on a case-by-case basis?

Thank you, I think this repo is really important and a good reference for how to do it properly. Maybe you should add some comments and link the Genome Biology paper ("Exaggerated false positives by popular differential expression methods when analyzing human population samples") to the repo. Yesterday, for example, I googled for a simialr problem and one of the fist links was this article, which happens to be an author of the aforementioned paper:
https://towardsdatascience.com/deseq2-and-edger-should-no-longer-be-the-default-choice-for-large-sample-differential-gene-8fdf008deae9

I guess the same flaws hold true as in the paper, and I find it dangerous that this is published with so much impact.

**Comment by mikelove** [comment]
Thanks for the comments and questions, 

1 and 2) This chunk of code here:

https://github.com/mikelove/preNivolumabOnNivolumab/blob/main/preNivolumabOnNivolumab.Rmd#L115

...is just the recommended code for RUVSeq. You could use median ratio and it would give roughly the same result. For more details on this particular choice, I recommend posting a question to the RUV developers on support site. RUVSeq wants raw counts, so here we do *not* correct for size factors when providing raw counts to RUVSeq:

https://github.com/mikelove/preNivolumabOnNivolumab/blob/main/preNivolumabOnNivolumab.Rmd#L114

3 + 4) Choice of `k` is indeed one that requires some deliberation on the part of the user. Here I didn't explore in depth what `k`, but just used a little intuition based on sample size and looking across a number of PCA / skree plots, with various labels for the known sample labels. If I were writing a paper I would investigate different `k` and motivate my choice with Supplementary Figures. Choosing `k=0` (ignoring batch) also requires justification. We've done this in the past, e.g. our RUV for Nanostring paper looks into the choice of `k`, as well as some eQTL collaborations I've worked on. In context of eQTL, I examine both positive controls and enrichment of cis eQTL (an expected pattern). Again, I think asking the RUV or SVA developers is appropriate, but they have also both written about choice of dimension for the unwanted variation space. In my opinion, `k` does depend on sample size. Practically, it must be less than sample size.

I wanted this repo to be constructive for biologists who want to know how to appropriately analyze large dataset which as a rule contain systematic (in this context, variation common to many genes, or "batch effects") variation in addition to the variation from the experiment design. Ignoring that variation will as a rule result in FP if a naive two group analysis is performed, but these can be effectively controlled. While looking at that example dataset did motivate my investigation, posting this repo and my thread on it 

https://twitter.com/mikelove/status/1513468597288452097

...is the extent of what I wanted to contribute to the conversation.

**Comment by chrarnold** [comment]
Thanks for the quick reply, enjoy #Bioc2022!
